export { PlatformClient } from './client'
export { ProjectsAPI } from './projects'
export type { Project, CreateProjectOpts } from './projects'
export { ServicesAPI, DeployHandle } from './services'
export type { Service, CreateServiceOpts, ScaleOpts, LogLine, DeployEvent } from './services'
export { AddonsAPI } from './addons'
export type { Addon, AddonType, CreateAddonOpts } from './addons'
export { SecretsAPI } from './secrets'
export type { Secret, SetSecretOpts } from './secrets'
export { DomainsAPI } from './domains'
export type { DomainInfo } from './domains'
export { MetricsAPI } from './metrics'
export type { MetricPoint, MetricRange, ServiceMetrics, CostMetrics } from './metrics'
